-- Production-safe seed file.
--
-- Core reference values (leagues, seasons, sizes, payment methods and commerce
-- settings) are created idempotently by migrations. Products, inventory,
-- orders and payment proofs must be loaded through the reviewed admin import
-- workflow, so this file intentionally contains no business records.
